### ISSUE TITLE
Aja: Interlaced video output appears to be missing one of the fields on SDI out

### ISSUE THREAD

**Issue by zduturan** [nodos-dev/workspace#19]
Reality 5.4.sp2.b0818

In interlaced IO mode (AjaIn and AjaOut are set to interlace), the output on SDI appears to be corrupt even though the monitor on Nodos editor shows a clean image.

Reproduction:
- Set AjaOut to interlaced mode
- Connect a "render" (Cyclorama, UE, etc.) to AjaOut
- Monitor the input of the AjaOut node via 1) Nodos Editor and 2) external monitor connected to Aja.
  - Both are fine.
- Add an AjaIn node and connect an interlaced video input to it.
- Monitor the input of the AjaOut node via 1) Nodos Editor and 2) external monitor connected to Aja.
  - Both are fine.
- Connect AjaIn’s output to the input of the rendering node (UE5 or Cyclorama)
- Monitor the input of the AjaOut node via 1) Nodos Editor and 2) external monitor connected to Aja.
  - Nodos Editor is fine.
  - Error: External monitor starts showing low quality video - as if one of the fields is being discarded.

Supporting documents:
- [Video when AjaIn is **not connected**](https://github.com/user-attachments/assets/5193df9e-a04b-4fba-9f75-b2bf74836fd1)
- [Video when AjaIn is **connected**](https://github.com/user-attachments/assets/7620515b-7838-41fe-a725-482ad2814af5)
- [Sample graph ](https://github.com/user-attachments/assets/8f6dd173-78f5-4040-94e1-7cd2c81e0d15)

**Comment by caner-milko** [comment]
Should be fixed with https://github.com/nodos-dev/bundler/releases/tag/v1.2.0.b3580-broadcast

**Comment by zduturan** [comment]
With Aja->Unreal->Aja, this is working fine, but we still see field oddities when we use the only Cyclorama node for rendering in between the AJAs. It's not easily noticeable but the issue is still there.

**Comment by candhyan** [comment]
and steps to reproduce? right now we can not reproduce

**Comment by zduturan** [comment]
Fixed via phone support and an update to Nodos.
